### ISSUE TITLE
Refant not provided to bandpass

### ISSUE THREAD

**Issue by surajit4444mondal** [binchensun/ovro-lwa-solar#18]
1. While refant has not been provided to gaincal, it is not used in bandpass. I am assigning myself for this task.
2. Add a kwargs feature in run_wsclean so that we can pass extra arguments to wsclean when needed for our daily usage without needing to rewrite it.
3. Remove the delayfile in make_fast_caltb_from_slow function in calibration.py
4. WSCLEAN does not append polarization stamp when it is called with single pol. Changes needed in utils.get_fast_vis_imagenames
5. Heliocentric coordinate registration and primary beam correction should take list of images. 
6. When bandpass table is made, it is made within the "caltables" folder, but when checking for existence, it does not search inside the caltables folder.

**Comment by surajit4444mondal** [comment]
I have fixed this issue and will raise a pull request as soon as I am done testing.. This is just to inform each other so that we do not redo stuff which has already been done.

**Comment by binchensun** [comment]
@surajit4444mondal I think this is already resolved in https://github.com/binchensun/ovro-lwa-solar/pull/23. Please close it if you agree.
